### ISSUE TITLE
Is there a way to avoid FxCopAnalyzers warnings?

### ISSUE THREAD

**Issue by aligneddev** [ardalis/GuardClauses#47]
We are using the Nuget package to help force better practices <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.7">

![image](https://user-images.githubusercontent.com/1636977/70247144-7feef780-173e-11ea-9b3a-3efc106e0ba2.png)

Is there a way for the GuardClauses to report to Roslyn that it's doing a null check so the warnings don't show? If so, I'd really like that feature

**Comment by ardalis** [comment]
Looking into it. See this thread:
https://twitter.com/ardalis/status/1202939577264148480

**Comment by ardalis** [comment]
I think this was fixed by #48. Reopen if not.

**Comment by aligneddev** [comment]
Unfortunately 1.3.2 doesn't fix it:

![image](https://user-images.githubusercontent.com/1636977/72537361-a629ac00-3841-11ea-8c84-724f8b749a2c.png)

Thanks for trying, I'll definitely use GuardClauses on other projects that don't have this analyzer or the rule turned on

**Comment by aligneddev** [comment]
It looks like release 1.4.1 fixes this. https://github.com/ardalis/GuardClauses/releases/tag/1.4.1

**Comment by ardalis** [comment]
It should, agreed!
