### ISSUE TITLE
CA1062: Validate arguments of public methods

### ISSUE THREAD

**Issue by pauldbentley** [ardalis/GuardClauses#59]
I get this warning quite a lot using GuardClauses - I think it's because the null check is in a separate assembly so the code analysis can't see that.

Do you find this as well; do you have any recommendations?  Thanks

**Comment by ardalis** [comment]
Yes, I think #57 addresses this. As soon as I have a chance to review and merge it a new version of the package should eliminate the warning, I hope.

**Comment by ardalis** [comment]
Hoping this was just fixed. Can you try it with version 1.4.0 from nuget.org?

**Comment by pauldbentley** [comment]
Hi Steve,

It didn't solve it directly (but it is a nice addition).

It is to do with how the Roslyn analyzers work.  Having read about [null-check-validation-methods](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#null-check-validation-methods), you can add the following to your `.editorconfig` file:

`dotnet_code_quality.null_check_validation_methods = Ardalis.GuardClauses.GuardClauseExtensions.Null(Ardalis.GuardClauses.IGuardClause,System.Object,System.String)`

This stops the warning.  You can do the same for `NullOrEmpty` and `NullOrWhiteSpace` buy using the | separator

**Comment by ardalis** [comment]
Hmm, is there anything I can do in the package itself so users don’t need to resort to editorconfig changes?

**Comment by pauldbentley** [comment]
> Hmm, is there anything I can do in the package itself so users don’t need to resort to editorconfig changes?

Yes, you can add a `ValidatedNotNullAttribute` and add to the `input` parameter.  This tells the Roslyn code analysis that the parameter has been validated as not null.

**Comment by ardalis** [comment]
Ah, like this?
https://stackoverflow.com/a/44005943

Thanks!

**Comment by pauldbentley** [comment]
Yep that's the one!

**Comment by ardalis** [comment]
Ok, added. Just published 1.4.1 which should be available on nuget shortly. Can you test it out and let me know if it (finally) fixes this problem? Thanks!

**Comment by pauldbentley** [comment]
Yes that fixes the problem!  There are now no warnings, and I don't need to make editorconfig changes.  Many thanks
